import type { Metadata } from "next";
import { Comforter } from "next/font/google";
import "./globals.css";

const comforter = Comforter({ subsets: ["latin"], weight: '400'})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comforter.className}>
        <div>111</div>
        {children}
      </body>
    </html>
  );
}
